### ISSUE TITLE
terminal colors bug

### ISSUE THREAD

**Issue by washonrails** [HydraVim/HydraVim#50]
misconfigured colors of terminal

![Captura de tela de 2023-03-22 01-28-54](https://user-images.githubusercontent.com/98850074/226802628-a6e1f5cc-9d1c-48d0-be5a-5a6d4bf1e6b8.png)

Closed for now , but still in background .. if this problem appears again , i will re-open this issue .  24/04/23

**Comment by Diogo-ss** [comment]
note: this problem still remains in the first startup, but after that it doesn't happen anymore.
